services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_USER=app_user
      - DB_PASSWORD=app_password
      - DB_NAME=hotel_management
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: hotel_management
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3308:3306" 
    volumes:
      - db_data:/var/lib/mysql
      - ./hotel_management.sql:/docker-entrypoint-initdb.d/hotel_management.sql
volumes:
  db_data: